/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitasjonRouteImport } from './routes/invitasjon'
import { Route as ProsjektProjectIdRouteImport } from './routes/prosjekt.$projectId'
import { Route as ProsjektProjectIdIndexRouteImport } from './routes/prosjekt.$projectId.index'
import { Route as ProsjektProjectIdBibliotekRouteImport } from './routes/prosjekt.$projectId.bibliotek'
import { Route as ProsjektProjectIdManusRouteImport } from './routes/prosjekt.$projectId.manus'
import { Route as ProsjektProjectIdSceneRouteImport } from './routes/prosjekt.$projectId.scene'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitasjonRoute = InvitasjonRouteImport.update({
  id: '/invitasjon',
  path: '/invitasjon',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsjektProjectIdRoute = ProsjektProjectIdRouteImport.update({
  id: '/prosjekt/$projectId',
  path: '/prosjekt/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsjektProjectIdIndexRoute = ProsjektProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProsjektProjectIdRoute,
} as any)
const ProsjektProjectIdBibliotekRoute =
  ProsjektProjectIdBibliotekRouteImport.update({
    id: '/bibliotek',
    path: '/bibliotek',
    getParentRoute: () => ProsjektProjectIdRoute,
  } as any)
const ProsjektProjectIdManusRoute = ProsjektProjectIdManusRouteImport.update({
  id: '/manus',
  path: '/manus',
  getParentRoute: () => ProsjektProjectIdRoute,
} as any)
const ProsjektProjectIdSceneRoute = ProsjektProjectIdSceneRouteImport.update({
  id: '/scene',
  path: '/scene',
  getParentRoute: () => ProsjektProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invitasjon': typeof InvitasjonRoute
  '/prosjekt/$projectId': typeof ProsjektProjectIdRouteWithChildren
  '/prosjekt/$projectId/bibliotek': typeof ProsjektProjectIdBibliotekRoute
  '/prosjekt/$projectId/manus': typeof ProsjektProjectIdManusRoute
  '/prosjekt/$projectId/scene': typeof ProsjektProjectIdSceneRoute
  '/prosjekt/$projectId/': typeof ProsjektProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invitasjon': typeof InvitasjonRoute
  '/prosjekt/$projectId/bibliotek': typeof ProsjektProjectIdBibliotekRoute
  '/prosjekt/$projectId/manus': typeof ProsjektProjectIdManusRoute
  '/prosjekt/$projectId/scene': typeof ProsjektProjectIdSceneRoute
  '/prosjekt/$projectId': typeof ProsjektProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invitasjon': typeof InvitasjonRoute
  '/prosjekt/$projectId': typeof ProsjektProjectIdRouteWithChildren
  '/prosjekt/$projectId/bibliotek': typeof ProsjektProjectIdBibliotekRoute
  '/prosjekt/$projectId/manus': typeof ProsjektProjectIdManusRoute
  '/prosjekt/$projectId/scene': typeof ProsjektProjectIdSceneRoute
  '/prosjekt/$projectId/': typeof ProsjektProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invitasjon'
    | '/prosjekt/$projectId'
    | '/prosjekt/$projectId/bibliotek'
    | '/prosjekt/$projectId/manus'
    | '/prosjekt/$projectId/scene'
    | '/prosjekt/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invitasjon'
    | '/prosjekt/$projectId/bibliotek'
    | '/prosjekt/$projectId/manus'
    | '/prosjekt/$projectId/scene'
    | '/prosjekt/$projectId'
  id:
    | '__root__'
    | '/'
    | '/invitasjon'
    | '/prosjekt/$projectId'
    | '/prosjekt/$projectId/bibliotek'
    | '/prosjekt/$projectId/manus'
    | '/prosjekt/$projectId/scene'
    | '/prosjekt/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvitasjonRoute: typeof InvitasjonRoute
  ProsjektProjectIdRoute: typeof ProsjektProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitasjon': {
      id: '/invitasjon'
      path: '/invitasjon'
      fullPath: '/invitasjon'
      preLoaderRoute: typeof InvitasjonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prosjekt/$projectId': {
      id: '/prosjekt/$projectId'
      path: '/prosjekt/$projectId'
      fullPath: '/prosjekt/$projectId'
      preLoaderRoute: typeof ProsjektProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prosjekt/$projectId/': {
      id: '/prosjekt/$projectId/'
      path: '/'
      fullPath: '/prosjekt/$projectId/'
      preLoaderRoute: typeof ProsjektProjectIdIndexRouteImport
      parentRoute: typeof ProsjektProjectIdRoute
    }
    '/prosjekt/$projectId/bibliotek': {
      id: '/prosjekt/$projectId/bibliotek'
      path: '/bibliotek'
      fullPath: '/prosjekt/$projectId/bibliotek'
      preLoaderRoute: typeof ProsjektProjectIdBibliotekRouteImport
      parentRoute: typeof ProsjektProjectIdRoute
    }
    '/prosjekt/$projectId/manus': {
      id: '/prosjekt/$projectId/manus'
      path: '/manus'
      fullPath: '/prosjekt/$projectId/manus'
      preLoaderRoute: typeof ProsjektProjectIdManusRouteImport
      parentRoute: typeof ProsjektProjectIdRoute
    }
    '/prosjekt/$projectId/scene': {
      id: '/prosjekt/$projectId/scene'
      path: '/scene'
      fullPath: '/prosjekt/$projectId/scene'
      preLoaderRoute: typeof ProsjektProjectIdSceneRouteImport
      parentRoute: typeof ProsjektProjectIdRoute
    }
  }
}

interface ProsjektProjectIdRouteChildren {
  ProsjektProjectIdBibliotekRoute: typeof ProsjektProjectIdBibliotekRoute
  ProsjektProjectIdManusRoute: typeof ProsjektProjectIdManusRoute
  ProsjektProjectIdSceneRoute: typeof ProsjektProjectIdSceneRoute
  ProsjektProjectIdIndexRoute: typeof ProsjektProjectIdIndexRoute
}

const ProsjektProjectIdRouteChildren: ProsjektProjectIdRouteChildren = {
  ProsjektProjectIdBibliotekRoute: ProsjektProjectIdBibliotekRoute,
  ProsjektProjectIdManusRoute: ProsjektProjectIdManusRoute,
  ProsjektProjectIdSceneRoute: ProsjektProjectIdSceneRoute,
  ProsjektProjectIdIndexRoute: ProsjektProjectIdIndexRoute,
}

const ProsjektProjectIdRouteWithChildren =
  ProsjektProjectIdRoute._addFileChildren(ProsjektProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvitasjonRoute: InvitasjonRoute,
  ProsjektProjectIdRoute: ProsjektProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
