/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitasjonRouteImport } from './routes/invitasjon'
import { Route as ProsjektProjectIdRouteImport } from './routes/prosjekt.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitasjonRoute = InvitasjonRouteImport.update({
  id: '/invitasjon',
  path: '/invitasjon',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsjektProjectIdRoute = ProsjektProjectIdRouteImport.update({
  id: '/prosjekt/$projectId',
  path: '/prosjekt/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invitasjon': typeof InvitasjonRoute
  '/prosjekt/$projectId': typeof ProsjektProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invitasjon': typeof InvitasjonRoute
  '/prosjekt/$projectId': typeof ProsjektProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invitasjon': typeof InvitasjonRoute
  '/prosjekt/$projectId': typeof ProsjektProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/invitasjon' | '/prosjekt/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/invitasjon' | '/prosjekt/$projectId'
  id: '__root__' | '/' | '/invitasjon' | '/prosjekt/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvitasjonRoute: typeof InvitasjonRoute
  ProsjektProjectIdRoute: typeof ProsjektProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitasjon': {
      id: '/invitasjon'
      path: '/invitasjon'
      fullPath: '/invitasjon'
      preLoaderRoute: typeof InvitasjonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prosjekt/$projectId': {
      id: '/prosjekt/$projectId'
      path: '/prosjekt/$projectId'
      fullPath: '/prosjekt/$projectId'
      preLoaderRoute: typeof ProsjektProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvitasjonRoute: InvitasjonRoute,
  ProsjektProjectIdRoute: ProsjektProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
